{{- if .Values.postgresInitScripts.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  labels:
    {{- include "cauldron-infra.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.postgresInitScripts.scripts }}
  {{ $filename }}: |-
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
