apiVersion: v1
kind: Secret
metadata:
  name: cauldron-secrets
  labels:
    {{- include "cauldron-infra.labels" . | nindent 4 }}
type: Opaque
data:
  db-root-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  timescale-password: {{ .Values.timescaledb.auth.password | b64enc | quote }}
  rabbitmq-user: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
