apiVersion: v2
name: cauldron-nextcloud
description: Helm chart for Nextcloud document store in the Cauldron sEOS
type: application
version: 0.1.0
appVersion: "27.1.2"
maintainers:
  - name: Cauldron Team
    email: info@cauldron.ai
dependencies:
  - name: common
    version: ~1.16.1
    repository: https://charts.bitnami.com/bitnami
