{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "cauldron-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cauldron-infra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: qdrant
  template:
    metadata:
      labels:
        {{- include "cauldron-infra.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: qdrant
    spec:
      containers:
      - name: qdrant
        image: "{{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}"
        imagePullPolicy: {{ .Values.qdrant.image.pullPolicy }}
        ports:
        - containerPort: 6333
          name: http
        - containerPort: 6334
          name: grpc
        volumeMounts:
        - name: qdrant-data
          mountPath: /qdrant/storage
        resources:
          {{- toYaml .Values.qdrant.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 6333
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 6333
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 1
      volumes:
      - name: qdrant-data
        persistentVolumeClaim:
          claimName: {{ include "qdrant.fullname" . }}-data
{{- end }}
