{{- if and .Values.redisInstances.enabled .Values.redisInstances.socketio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-socketio
  labels:
    {{- include "cauldron-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-socketio
spec:
  selector:
    {{- include "cauldron-infra.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis-socketio
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
{{- end }}
