apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: cauldron-staging

commonLabels:
  environment: staging

patches:
  - path: patches/ingress-patch.yaml
  - path: patches/replicas-patch.yaml
  - path: patches/resources-patch.yaml

configMapGenerator:
  - name: cauldron-staging-config
    literals:
      - ENVIRONMENT=staging

secretGenerator:
  - name: cauldron-secrets
    behavior: replace
    envs:
      - secrets.env
