apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cauldron-frappe.fullname" . }}-secret
  labels:
    {{- include "cauldron-frappe.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.frappe.site.adminPassword | b64enc | quote }}
