{{- if .Values.nextcloud.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cauldron-nextcloud.pvcName" . }}
  labels:
    {{- include "cauldron-nextcloud.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.nextcloud.persistence.accessMode }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.nextcloud.persistence.size }}
{{- end }}
