{{- if not .Values.nextcloud.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cauldron-nextcloud.secretName" . }}
  labels:
    {{- include "cauldron-nextcloud.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.nextcloud.admin.existingSecretPasswordKey }}: {{ .Values.nextcloud.admin.password | b64enc | quote }}
{{- end }}
