apiVersion: v1
kind: Service
metadata:
  name: {{ include "cauldron-nextcloud.fullname" . }}
  labels:
    {{- include "cauldron-nextcloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nextcloud.service.type }}
  ports:
    - port: {{ .Values.nextcloud.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cauldron-nextcloud.selectorLabels" . | nindent 4 }}
