apiVersion: v1
kind: Secret
metadata:
  name: cauldron-secrets
type: Opaque
data:
  # These are placeholder values. In a real environment, you would use proper secrets management
  # Base64 encoded values: echo -n "your-value" | base64
  db-root-password: cGxlYXNlX2NoYW5nZV9pbl9lbnY=  # please_change_in_env
  timescale-password: cGxlYXNlX2NoYW5nZV9pbl9lbnY=  # please_change_in_env
  rabbitmq-user: Z3Vlc3Q=  # guest
  rabbitmq-password: Z3Vlc3Q=  # guest
  superagi-api-key: ""  # Add your SuperAGI API key
  openai-api-key: ""  # Add your OpenAI API key
  anthropic-api-key: ""  # Add your Anthropic API key
  huggingface-token: ""  # Add your Hugging Face token
