apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: cauldron-dev

commonLabels:
  environment: dev

patches:
  - path: patches/ingress-patch.yaml
  - path: patches/replicas-patch.yaml

configMapGenerator:
  - name: cauldron-dev-config
    literals:
      - ENVIRONMENT=dev

secretGenerator:
  - name: cauldron-secrets
    behavior: replace
    envs:
      - secrets.env
