{{- if .Values.timescaledb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    {{- include "cauldron-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: timescaledb
spec:
  selector:
    {{- include "cauldron-infra.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: timescaledb
  ports:
  - port: {{ .Values.timescaledb.service.port }}
    targetPort: 5432
    name: postgres
  type: ClusterIP
{{- end }}
