apiVersion: v2
name: cauldron-infra
description: Helm chart for Cauldron infrastructure dependencies
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Cauldron Team
    email: info@cauldron.ai
dependencies:
  - name: postgresql
    version: ~12.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: ~11.16.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: ~17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
