# Staging environment values for cauldron-infra

global:
  environment: staging

# PostgreSQL configuration for staging
postgresql:
  primary:
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  persistence:
    size: 20Gi
  metrics:
    enabled: true

# TimescaleDB configuration for staging
timescaledb:
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  persistence:
    size: 20Gi

# Qdrant configuration for staging
qdrant:
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  persistence:
    size: 10Gi

# RabbitMQ configuration for staging
rabbitmq:
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  persistence:
    size: 10Gi
  replicaCount: 2
  metrics:
    enabled: true

# Redis configuration for staging
redis:
  master:
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    persistence:
      enabled: true
      size: 5Gi
  metrics:
    enabled: true

# Redis instances for Frappe/ERPNext in staging
redisInstances:
  cache:
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  queue:
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  socketio:
    resources:
      requests:
        memory: "256Mi"
        cpu: "125m"
      limits:
        memory: "512Mi"
        cpu: "250m"
