# Production environment values for cauldron-frappe

global:
  environment: prod

# Frappe configuration for production
frappe:
  # Resource configuration for production
  resources:
    web:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    worker:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    scheduler:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    socketio:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  
  # Persistence configuration for production
  persistence:
    size: 50Gi
  
  # Replica configuration for production
  replicas:
    web: 3
    worker: 3
    scheduler: 1
    socketio: 3
  
  # Ingress configuration for production
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: cauldron.ai
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: cauldron-prod-tls
        hosts:
          - cauldron.ai
  
  # Bench configuration for production
  bench:
    developerMode: false
    autoUpdate: false
