apiVersion: v2
name: cauldron-manifold
description: Helm chart for Cauldron™ Manifold UI frontend application
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Cauldron Team
    email: info@cauldron.ai
dependencies:
  - name: common
    version: ~1.16.1
    repository: https://charts.bitnami.com/bitnami
