# Production environment values for cauldron-manifold

global:
  environment: prod

# Manifold UI configuration for production
manifold:
  # Image configuration for production
  image:
    tag: "latest"
    pullPolicy: Always
  
  # Resource configuration for production
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  # Replica configuration for production
  replicas: 3
  
  # Ingress configuration for production
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: cauldron.ai
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: manifold-prod-tls
        hosts:
          - cauldron.ai
  
  # API configuration for production
  api:
    url: "/api"
  
  # Autoscaling configuration for production
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
